services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - MODEL_NAME=llama3.2:2b
    command: [ "--model", "llama3.2:2b" ]

volumes:
  ollama-data: